select * from hospital.treatment;
INSERT INTO hospital.doctor VALUES(6, 'Charles Schultz', '1965-11-11', 'Pediatrics', 1);
INSERT INTO hospital.doctor(doctorID, doctorName, doctorBirthDate, DoctorEmployedAt) VALUES(21, 'Celestina Warbeck', '1970-01-01', 1);
INSERT INTO hospital.ward VALUES (1, 'CCU', 'North wing');
INSERT INTO hospital.ward VALUES (3, 'Rehabilitation', 'Southwest wing');
INSERT INTO hospital.patient VALUES (2, 'John Wick', '1993-03-02');
INSERT INTO hospital.patient VALUES (92, 'Mike Ritch', '1978-06-30');
INSERT INTO hospital.medicine VALUES (1, 'Aspirin', 2000);
INSERT INTO hospital.medicine VALUES (2, 'Dulcolax', 3000);
INSERT INTO hospital.medicine VALUES (3, 'Xanax', 666);
INSERT INTO hospital.prescription VALUES (92, 2, 30);
INSERT INTO hospital.prescription VALUES (92, 3, 20);
INSERT INTO hospital.prescription VALUES (2, 3, 60);
INSERT INTO hospital.treatment VALUES (2, 1, '2020-06-08', 'arrhytmia');
INSERT INTO hospital.treatment(treatmentPatient, treatmentWard, treatmentAdmissionDate) VALUES (92, 3, '2020-10-13');
INSERT INTO hospital.allergy VALUES (2, 'Lactose');
INSERT INTO hospital.allergy VALUES (2, 'Penicillin');
INSERT INTO hospital.allergy VALUES (92, 'Gluten');